services:
  mongo-db:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped    #Restarta o container automaticamente caso tenha algum problema
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]  # Inicia o MongoDB com o replica set ativado e listeners para todas as interfaces
    ports:
      - "27017:27017"
    healthcheck:    #Healthcheck para o docker entender quando o mongo esta pronto/saudavel
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - mongo-data:/data/db    #Utiliza um volume persistene no host, evita perder os dados em caso de restart do container
      - ./mongo-init:/docker-entrypoint-initdb.d    #Script para popular inciar os replicasets e popular o banco, executado apenas quando o container é criado

  app:
    build: .    #Builda a imagem da aplicação com base no dockerfile
    container_name: saque-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/saque-db    #Define a string de conexão com banco, via variavel de ambiente
                                                                    #Não utiliza localhost, pois dentro da "rede do docker" ele precisa usar o nome do serviço
      SERVER_ERROR_INCLUDE_MESSAGE: always
    depends_on:    #Garante que a aplicação so vai ser executada apenas quando o mongo ja estiver saudavel
      mongo-db:
        condition: service_healthy

  test:
    build:
      context: .
      target: test   # build do stage de teste do Dockerfile
    container_name: saque-tests
    depends_on:
      mongo-db:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/saque-db

volumes:
  mongo-data: